#!/usr/bin/env -S sbcl --script
(load "~/.sbclrc")
(defun indifference()
  (defvar good1)
  (defvar good2)
  (defvar price1)
  (defvar price2)
  (defvar budget)
  (defvar utility)
  (format t "When it comes to goods, in the neoclassical school of economics you can model which goods to buy using indifference curve, which measures at what point you are indifferent between 2 goods.")
  (terpri)
  (format t "Although making a whole curve is outside the scope of this , I can use budget to maximize utility at that budget between 2 goods.")
  (terpri)
  (format t "So give the names of the two goods you wish to compare?")
  (terpri)
  (setq good1 (read))
  (setq good2 (read))
  (format t "Now give the prices of the goods respectively")
  (terpri)
  (setq price1 (read))
  (setq price2 (read))
  (format t "We also need a total budget for these 2 goods")
  (terpri)
  (setq budget (read))
  (format t "How much do you value the first good relative to the second good?")
  (terpri)
  (setq utility (read)))
